### PR TITLE
Fix compilation for rustc > 1.80

### PR DESCRIPTION
**Pull request by picnoir**
Fix the build for rustc > 1.80.

Fix https://github.com/twosigma/nsncd/issues/118

### CODE REVIEW

**Comment by picnoir** [comment]
Not good enough.

**Comment by picnoir** [comment]
Okay, this is ready.

I don't understand the Debian failure.

This is blocking for NixOS. See https://github.com/NixOS/nixpkgs/pull/332176 for more details.

We should probably cut out a new release once this PR is ready and merged.

**Comment by leifwalsh** [comment]
I don't understand the Debian build failure either but it's been persistent. I'll ask someone who knows Debian more to take a look, I'd like to get this and #110 merged, as well as some of the dependabot things.

**Comment by leifwalsh** [comment]
We dealt with this in #123

**Pull request closed without merging**
